### ISSUE TITLE
Improvement suggestion PUF search interface

### ISSUE THREAD

**Issue by marcosjviana** [lmb-embrapa/machado#241]
To facilitate the search for PUF annotations, they could enable the ordering of the proteins of the same orthologous group (when I enter to check all the proteins of a certain group) by the Display (Annotation).

Or even allowing to download the list of all proteins of a certain orthologous group, just as they did when listing the PUFs of an organism.

**Comment by azneto** [comment]
Hi Marcos, 
The improvements should be available to every feature, PUF or not. 

Based on your comment, the feature you're seeking is the 'column sorting', right? So that you can sort the search results based on any column, such as, orthologous group or display. If that's the case, we'll create a specific issue to address it.

In regard to the second part of your comment, you can just click the link in the orthologous group and the proteins will be listed, as well as the download buttons (.tsv and .fasta).

**Comment by azneto** [comment]
I was testing the orthologous group link, but the download buttons are not showing properly. In order to make them show, you need to select 'polypeptide' in the 'Sequence type' filter. 

I'll create an issue to fix it.

**Comment by marcosjviana** [comment]
> 
> 
> Hi Marcos,
> The improvements should be available to every feature, PUF or not.
> 
> Based on your comment, the feature you're seeking is the 'column sorting', right? So that you can sort the search results based on any column, such as, orthologous group or display. If that's the case, we'll create a specific issue to address it.
> 
> In regard to the second part of your comment, you can just click the link in the orthologous group and the proteins will be listed, as well as the download buttons (.tsv and .fasta).
